version: '3.8'
services:
  postgresql:
    container_name: postgresql
    image: postgres:14.11
    environment:
      POSTGRES_PASSWORD: taskboard
      POSTGRES_USER: taskboard
    # Use versions that are configured in .carbon/modules/communications_archive
    ports:
      - '5432:5432'
    volumes:
      - /var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready --username=taskboard" ]
      interval: 2s
      timeout: 60s
      retries: 10
